version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - umbrel_main_network  # Rede do Umbrel

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "2180:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Umbrel Kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:9093"
      KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper
      - kafka

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE_PORT: 9093
      KAFKA_LISTENER_NAME_INSIDE: INSIDE://kafka:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    depends_on:
      - zookeeper
    networks:
      - umbrel_main_network  # Rede do Umbrel

networks:
  umbrel_main_network:
    external: true  # Indica que estamos usando uma rede externa, já existente