version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:3.0.0
    depends_on:
      - postgres
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${APP_AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ${APP_DATA_DIR}/dags:/opt/airflow/dags
      - ${APP_DATA_DIR}/logs:/opt/airflow/logs
      - ${APP_DATA_DIR}/plugins:/opt/airflow/plugins
      - ${APP_DATA_DIR}/scripts:/opt/airflow/scripts
    ports:
      - "8081:8080"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create
          --username admin
          --firstname Admin
          --lastname User
          --role Admin
          --email admin@example.com
          --password admin &&
        airflow webserver
      "

volumes:
  postgres_data: