version: "3.8"

services:
  airflow:
    image: apache/airflow:3.0.0
    container_name: airflow
    restart: always
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ${APP_AIRFLOW_FERNET_KEY}
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    command: standalone
    ports:
      - "8081:8080"
    volumes:
      - ${APP_DATA_DIR}/dags:/opt/airflow/dags
      - ${APP_DATA_DIR}/logs:/opt/airflow/logs
      - ${APP_DATA_DIR}/plugins:/opt/airflow/plugins
      - ${APP_DATA_DIR}/db:/opt/airflow/standalone_admin.db